### PR TITLE
Patch for disabling windows group focus, through an optional setting.

### PR DESCRIPTION
**Pull request by Turbine1991**
I've based it off your branch and tested it. I won't take any offense if you improve the wording in the settings area.

Screenshot from 2021-03-20 10-18-52

### CODE REVIEW

**Comment by Leleat** [comment]
Looks good, I'll change the wording of the tooltip a bit in a separate commit.

Thanks for the contribution!

**Comment by job1925** [comment]
Sorry to bother you again, but shouldn't it be "Enable window group focus" and ON by default like the other two switches in the settings?

**Comment by Turbine1991** [comment]
I was actually going to do a settings update to fix this and a few other inconsistencies once you've accepted my last pull request.

**Comment by Turbine1991** [comment]
Rename "Enable tiling dash" to just be "Dash" or "Window dash".

"Enable Animations" to Animations.

And the last "Group focus". What do you think?

**Comment by Leleat** [comment]
> "Enable window group focus" and ON by default

Yeah, makes sense.

> Yes. I was actually going to do a settings consistency overhaul to fix this and a few other inconsistencies once you've accepted my last pull request.

> Rename "Enable tiling dash" to just be "Dash" or "Tiling dash".
"Enable Animations" to Animations.
And the last "Group focus".

Sure, thank you!

While you are at it please remove the `Useful when in taskbar/always visible dock mode` line since that is too user-specific.

**Comment by Turbine1991** [comment]
> > "Enable window group focus" and ON by default
> 
> Yeah, makes sense.
> 
> > Yes. I was actually going to do a settings consistency overhaul to fix this and a few other inconsistencies once you've accepted my last pull request.
> 
> > Rename "Enable tiling dash" to just be "Dash" or "Tiling dash".
> > "Enable Animations" to Animations.
> > And the last "Group focus".
> 
> Sure, thank you!
> 
> While you are at it please remove the `Useful when in taskbar/always visible dock mode` line since that is too user-specific.

Sure thing.

**Pull request merged**
